/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.siriusdb.thrift.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * Master告知Region当前状态请求
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2021-05-26")
public class NotifyStateRequest implements org.apache.thrift.TBase<NotifyStateRequest, NotifyStateRequest._Fields>, java.io.Serializable, Cloneable, Comparable<NotifyStateRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NotifyStateRequest");

  private static final org.apache.thrift.protocol.TField STATE_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("stateCode", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DUAL_SERVER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("dualServerName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DUAL_SERVER_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("dualServerUrl", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField BASE_FIELD_DESC = new org.apache.thrift.protocol.TField("base", org.apache.thrift.protocol.TType.STRUCT, (short)255);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new NotifyStateRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new NotifyStateRequestTupleSchemeFactory());
  }

  public int stateCode; // required
  public String dualServerName; // required
  public String dualServerUrl; // required
  public com.siriusdb.thrift.model.Base base; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STATE_CODE((short)1, "stateCode"),
    DUAL_SERVER_NAME((short)2, "dualServerName"),
    DUAL_SERVER_URL((short)3, "dualServerUrl"),
    BASE((short)255, "base");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STATE_CODE
          return STATE_CODE;
        case 2: // DUAL_SERVER_NAME
          return DUAL_SERVER_NAME;
        case 3: // DUAL_SERVER_URL
          return DUAL_SERVER_URL;
        case 255: // BASE
          return BASE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STATECODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATE_CODE, new org.apache.thrift.meta_data.FieldMetaData("stateCode", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DUAL_SERVER_NAME, new org.apache.thrift.meta_data.FieldMetaData("dualServerName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DUAL_SERVER_URL, new org.apache.thrift.meta_data.FieldMetaData("dualServerUrl", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BASE, new org.apache.thrift.meta_data.FieldMetaData("base", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.siriusdb.thrift.model.Base.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NotifyStateRequest.class, metaDataMap);
  }

  public NotifyStateRequest() {
  }

  public NotifyStateRequest(
    int stateCode,
    String dualServerName,
    String dualServerUrl,
    com.siriusdb.thrift.model.Base base)
  {
    this();
    this.stateCode = stateCode;
    setStateCodeIsSet(true);
    this.dualServerName = dualServerName;
    this.dualServerUrl = dualServerUrl;
    this.base = base;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NotifyStateRequest(NotifyStateRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    this.stateCode = other.stateCode;
    if (other.isSetDualServerName()) {
      this.dualServerName = other.dualServerName;
    }
    if (other.isSetDualServerUrl()) {
      this.dualServerUrl = other.dualServerUrl;
    }
    if (other.isSetBase()) {
      this.base = new com.siriusdb.thrift.model.Base(other.base);
    }
  }

  public NotifyStateRequest deepCopy() {
    return new NotifyStateRequest(this);
  }

  @Override
  public void clear() {
    setStateCodeIsSet(false);
    this.stateCode = 0;
    this.dualServerName = null;
    this.dualServerUrl = null;
    this.base = null;
  }

  public int getStateCode() {
    return this.stateCode;
  }

  public NotifyStateRequest setStateCode(int stateCode) {
    this.stateCode = stateCode;
    setStateCodeIsSet(true);
    return this;
  }

  public void unsetStateCode() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STATECODE_ISSET_ID);
  }

  /** Returns true if field stateCode is set (has been assigned a value) and false otherwise */
  public boolean isSetStateCode() {
    return EncodingUtils.testBit(__isset_bitfield, __STATECODE_ISSET_ID);
  }

  public void setStateCodeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STATECODE_ISSET_ID, value);
  }

  public String getDualServerName() {
    return this.dualServerName;
  }

  public NotifyStateRequest setDualServerName(String dualServerName) {
    this.dualServerName = dualServerName;
    return this;
  }

  public void unsetDualServerName() {
    this.dualServerName = null;
  }

  /** Returns true if field dualServerName is set (has been assigned a value) and false otherwise */
  public boolean isSetDualServerName() {
    return this.dualServerName != null;
  }

  public void setDualServerNameIsSet(boolean value) {
    if (!value) {
      this.dualServerName = null;
    }
  }

  public String getDualServerUrl() {
    return this.dualServerUrl;
  }

  public NotifyStateRequest setDualServerUrl(String dualServerUrl) {
    this.dualServerUrl = dualServerUrl;
    return this;
  }

  public void unsetDualServerUrl() {
    this.dualServerUrl = null;
  }

  /** Returns true if field dualServerUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetDualServerUrl() {
    return this.dualServerUrl != null;
  }

  public void setDualServerUrlIsSet(boolean value) {
    if (!value) {
      this.dualServerUrl = null;
    }
  }

  public com.siriusdb.thrift.model.Base getBase() {
    return this.base;
  }

  public NotifyStateRequest setBase(com.siriusdb.thrift.model.Base base) {
    this.base = base;
    return this;
  }

  public void unsetBase() {
    this.base = null;
  }

  /** Returns true if field base is set (has been assigned a value) and false otherwise */
  public boolean isSetBase() {
    return this.base != null;
  }

  public void setBaseIsSet(boolean value) {
    if (!value) {
      this.base = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STATE_CODE:
      if (value == null) {
        unsetStateCode();
      } else {
        setStateCode((Integer)value);
      }
      break;

    case DUAL_SERVER_NAME:
      if (value == null) {
        unsetDualServerName();
      } else {
        setDualServerName((String)value);
      }
      break;

    case DUAL_SERVER_URL:
      if (value == null) {
        unsetDualServerUrl();
      } else {
        setDualServerUrl((String)value);
      }
      break;

    case BASE:
      if (value == null) {
        unsetBase();
      } else {
        setBase((com.siriusdb.thrift.model.Base)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STATE_CODE:
      return getStateCode();

    case DUAL_SERVER_NAME:
      return getDualServerName();

    case DUAL_SERVER_URL:
      return getDualServerUrl();

    case BASE:
      return getBase();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STATE_CODE:
      return isSetStateCode();
    case DUAL_SERVER_NAME:
      return isSetDualServerName();
    case DUAL_SERVER_URL:
      return isSetDualServerUrl();
    case BASE:
      return isSetBase();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof NotifyStateRequest)
      return this.equals((NotifyStateRequest)that);
    return false;
  }

  public boolean equals(NotifyStateRequest that) {
    if (that == null)
      return false;

    boolean this_present_stateCode = true;
    boolean that_present_stateCode = true;
    if (this_present_stateCode || that_present_stateCode) {
      if (!(this_present_stateCode && that_present_stateCode))
        return false;
      if (this.stateCode != that.stateCode)
        return false;
    }

    boolean this_present_dualServerName = true && this.isSetDualServerName();
    boolean that_present_dualServerName = true && that.isSetDualServerName();
    if (this_present_dualServerName || that_present_dualServerName) {
      if (!(this_present_dualServerName && that_present_dualServerName))
        return false;
      if (!this.dualServerName.equals(that.dualServerName))
        return false;
    }

    boolean this_present_dualServerUrl = true && this.isSetDualServerUrl();
    boolean that_present_dualServerUrl = true && that.isSetDualServerUrl();
    if (this_present_dualServerUrl || that_present_dualServerUrl) {
      if (!(this_present_dualServerUrl && that_present_dualServerUrl))
        return false;
      if (!this.dualServerUrl.equals(that.dualServerUrl))
        return false;
    }

    boolean this_present_base = true && this.isSetBase();
    boolean that_present_base = true && that.isSetBase();
    if (this_present_base || that_present_base) {
      if (!(this_present_base && that_present_base))
        return false;
      if (!this.base.equals(that.base))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_stateCode = true;
    list.add(present_stateCode);
    if (present_stateCode)
      list.add(stateCode);

    boolean present_dualServerName = true && (isSetDualServerName());
    list.add(present_dualServerName);
    if (present_dualServerName)
      list.add(dualServerName);

    boolean present_dualServerUrl = true && (isSetDualServerUrl());
    list.add(present_dualServerUrl);
    if (present_dualServerUrl)
      list.add(dualServerUrl);

    boolean present_base = true && (isSetBase());
    list.add(present_base);
    if (present_base)
      list.add(base);

    return list.hashCode();
  }

  @Override
  public int compareTo(NotifyStateRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStateCode()).compareTo(other.isSetStateCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStateCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stateCode, other.stateCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDualServerName()).compareTo(other.isSetDualServerName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDualServerName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dualServerName, other.dualServerName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDualServerUrl()).compareTo(other.isSetDualServerUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDualServerUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dualServerUrl, other.dualServerUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBase()).compareTo(other.isSetBase());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBase()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.base, other.base);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("NotifyStateRequest(");
    boolean first = true;

    sb.append("stateCode:");
    sb.append(this.stateCode);
    first = false;
    if (!first) sb.append(", ");
    sb.append("dualServerName:");
    if (this.dualServerName == null) {
      sb.append("null");
    } else {
      sb.append(this.dualServerName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dualServerUrl:");
    if (this.dualServerUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.dualServerUrl);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("base:");
    if (this.base == null) {
      sb.append("null");
    } else {
      sb.append(this.base);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'stateCode' because it's a primitive and you chose the non-beans generator.
    if (dualServerName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'dualServerName' was not present! Struct: " + toString());
    }
    if (dualServerUrl == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'dualServerUrl' was not present! Struct: " + toString());
    }
    if (base == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'base' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (base != null) {
      base.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NotifyStateRequestStandardSchemeFactory implements SchemeFactory {
    public NotifyStateRequestStandardScheme getScheme() {
      return new NotifyStateRequestStandardScheme();
    }
  }

  private static class NotifyStateRequestStandardScheme extends StandardScheme<NotifyStateRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NotifyStateRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STATE_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.stateCode = iprot.readI32();
              struct.setStateCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DUAL_SERVER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dualServerName = iprot.readString();
              struct.setDualServerNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DUAL_SERVER_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dualServerUrl = iprot.readString();
              struct.setDualServerUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 255: // BASE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.base = new com.siriusdb.thrift.model.Base();
              struct.base.read(iprot);
              struct.setBaseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetStateCode()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'stateCode' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NotifyStateRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(STATE_CODE_FIELD_DESC);
      oprot.writeI32(struct.stateCode);
      oprot.writeFieldEnd();
      if (struct.dualServerName != null) {
        oprot.writeFieldBegin(DUAL_SERVER_NAME_FIELD_DESC);
        oprot.writeString(struct.dualServerName);
        oprot.writeFieldEnd();
      }
      if (struct.dualServerUrl != null) {
        oprot.writeFieldBegin(DUAL_SERVER_URL_FIELD_DESC);
        oprot.writeString(struct.dualServerUrl);
        oprot.writeFieldEnd();
      }
      if (struct.base != null) {
        oprot.writeFieldBegin(BASE_FIELD_DESC);
        struct.base.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NotifyStateRequestTupleSchemeFactory implements SchemeFactory {
    public NotifyStateRequestTupleScheme getScheme() {
      return new NotifyStateRequestTupleScheme();
    }
  }

  private static class NotifyStateRequestTupleScheme extends TupleScheme<NotifyStateRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NotifyStateRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.stateCode);
      oprot.writeString(struct.dualServerName);
      oprot.writeString(struct.dualServerUrl);
      struct.base.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NotifyStateRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.stateCode = iprot.readI32();
      struct.setStateCodeIsSet(true);
      struct.dualServerName = iprot.readString();
      struct.setDualServerNameIsSet(true);
      struct.dualServerUrl = iprot.readString();
      struct.setDualServerUrlIsSet(true);
      struct.base = new com.siriusdb.thrift.model.Base();
      struct.base.read(iprot);
      struct.setBaseIsSet(true);
    }
  }

}

