/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.siriusdb.thrift.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * 表格元数据的数据结构
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2021-06-07")
public class VTableMeta implements org.apache.thrift.TBase<VTableMeta, VTableMeta._Fields>, java.io.Serializable, Cloneable, Comparable<VTableMeta> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("VTableMeta");

  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PRIMARY_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("primaryKey", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ATTRIBUTES_FIELD_DESC = new org.apache.thrift.protocol.TField("attributes", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField LOCATED_SERVER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("locatedServerName", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField LOCATED_SERVER_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("locatedServerUrl", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new VTableMetaStandardSchemeFactory());
    schemes.put(TupleScheme.class, new VTableMetaTupleSchemeFactory());
  }

  public String name; // required
  public String primaryKey; // required
  public List<VAttribute> attributes; // required
  public String locatedServerName; // required
  public String locatedServerUrl; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    PRIMARY_KEY((short)2, "primaryKey"),
    ATTRIBUTES((short)3, "attributes"),
    LOCATED_SERVER_NAME((short)4, "locatedServerName"),
    LOCATED_SERVER_URL((short)5, "locatedServerUrl");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // PRIMARY_KEY
          return PRIMARY_KEY;
        case 3: // ATTRIBUTES
          return ATTRIBUTES;
        case 4: // LOCATED_SERVER_NAME
          return LOCATED_SERVER_NAME;
        case 5: // LOCATED_SERVER_URL
          return LOCATED_SERVER_URL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRIMARY_KEY, new org.apache.thrift.meta_data.FieldMetaData("primaryKey", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ATTRIBUTES, new org.apache.thrift.meta_data.FieldMetaData("attributes", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, VAttribute.class))));
    tmpMap.put(_Fields.LOCATED_SERVER_NAME, new org.apache.thrift.meta_data.FieldMetaData("locatedServerName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LOCATED_SERVER_URL, new org.apache.thrift.meta_data.FieldMetaData("locatedServerUrl", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(VTableMeta.class, metaDataMap);
  }

  public VTableMeta() {
  }

  public VTableMeta(
    String name,
    String primaryKey,
    List<VAttribute> attributes,
    String locatedServerName,
    String locatedServerUrl)
  {
    this();
    this.name = name;
    this.primaryKey = primaryKey;
    this.attributes = attributes;
    this.locatedServerName = locatedServerName;
    this.locatedServerUrl = locatedServerUrl;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public VTableMeta(VTableMeta other) {
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetPrimaryKey()) {
      this.primaryKey = other.primaryKey;
    }
    if (other.isSetAttributes()) {
      List<VAttribute> __this__attributes = new ArrayList<VAttribute>(other.attributes.size());
      for (VAttribute other_element : other.attributes) {
        __this__attributes.add(new VAttribute(other_element));
      }
      this.attributes = __this__attributes;
    }
    if (other.isSetLocatedServerName()) {
      this.locatedServerName = other.locatedServerName;
    }
    if (other.isSetLocatedServerUrl()) {
      this.locatedServerUrl = other.locatedServerUrl;
    }
  }

  public VTableMeta deepCopy() {
    return new VTableMeta(this);
  }

  @Override
  public void clear() {
    this.name = null;
    this.primaryKey = null;
    this.attributes = null;
    this.locatedServerName = null;
    this.locatedServerUrl = null;
  }

  public String getName() {
    return this.name;
  }

  public VTableMeta setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public String getPrimaryKey() {
    return this.primaryKey;
  }

  public VTableMeta setPrimaryKey(String primaryKey) {
    this.primaryKey = primaryKey;
    return this;
  }

  public void unsetPrimaryKey() {
    this.primaryKey = null;
  }

  /** Returns true if field primaryKey is set (has been assigned a value) and false otherwise */
  public boolean isSetPrimaryKey() {
    return this.primaryKey != null;
  }

  public void setPrimaryKeyIsSet(boolean value) {
    if (!value) {
      this.primaryKey = null;
    }
  }

  public int getAttributesSize() {
    return (this.attributes == null) ? 0 : this.attributes.size();
  }

  public java.util.Iterator<VAttribute> getAttributesIterator() {
    return (this.attributes == null) ? null : this.attributes.iterator();
  }

  public void addToAttributes(VAttribute elem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<VAttribute>();
    }
    this.attributes.add(elem);
  }

  public List<VAttribute> getAttributes() {
    return this.attributes;
  }

  public VTableMeta setAttributes(List<VAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public void unsetAttributes() {
    this.attributes = null;
  }

  /** Returns true if field attributes is set (has been assigned a value) and false otherwise */
  public boolean isSetAttributes() {
    return this.attributes != null;
  }

  public void setAttributesIsSet(boolean value) {
    if (!value) {
      this.attributes = null;
    }
  }

  public String getLocatedServerName() {
    return this.locatedServerName;
  }

  public VTableMeta setLocatedServerName(String locatedServerName) {
    this.locatedServerName = locatedServerName;
    return this;
  }

  public void unsetLocatedServerName() {
    this.locatedServerName = null;
  }

  /** Returns true if field locatedServerName is set (has been assigned a value) and false otherwise */
  public boolean isSetLocatedServerName() {
    return this.locatedServerName != null;
  }

  public void setLocatedServerNameIsSet(boolean value) {
    if (!value) {
      this.locatedServerName = null;
    }
  }

  public String getLocatedServerUrl() {
    return this.locatedServerUrl;
  }

  public VTableMeta setLocatedServerUrl(String locatedServerUrl) {
    this.locatedServerUrl = locatedServerUrl;
    return this;
  }

  public void unsetLocatedServerUrl() {
    this.locatedServerUrl = null;
  }

  /** Returns true if field locatedServerUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetLocatedServerUrl() {
    return this.locatedServerUrl != null;
  }

  public void setLocatedServerUrlIsSet(boolean value) {
    if (!value) {
      this.locatedServerUrl = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case PRIMARY_KEY:
      if (value == null) {
        unsetPrimaryKey();
      } else {
        setPrimaryKey((String)value);
      }
      break;

    case ATTRIBUTES:
      if (value == null) {
        unsetAttributes();
      } else {
        setAttributes((List<VAttribute>)value);
      }
      break;

    case LOCATED_SERVER_NAME:
      if (value == null) {
        unsetLocatedServerName();
      } else {
        setLocatedServerName((String)value);
      }
      break;

    case LOCATED_SERVER_URL:
      if (value == null) {
        unsetLocatedServerUrl();
      } else {
        setLocatedServerUrl((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME:
      return getName();

    case PRIMARY_KEY:
      return getPrimaryKey();

    case ATTRIBUTES:
      return getAttributes();

    case LOCATED_SERVER_NAME:
      return getLocatedServerName();

    case LOCATED_SERVER_URL:
      return getLocatedServerUrl();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NAME:
      return isSetName();
    case PRIMARY_KEY:
      return isSetPrimaryKey();
    case ATTRIBUTES:
      return isSetAttributes();
    case LOCATED_SERVER_NAME:
      return isSetLocatedServerName();
    case LOCATED_SERVER_URL:
      return isSetLocatedServerUrl();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof VTableMeta)
      return this.equals((VTableMeta)that);
    return false;
  }

  public boolean equals(VTableMeta that) {
    if (that == null)
      return false;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_primaryKey = true && this.isSetPrimaryKey();
    boolean that_present_primaryKey = true && that.isSetPrimaryKey();
    if (this_present_primaryKey || that_present_primaryKey) {
      if (!(this_present_primaryKey && that_present_primaryKey))
        return false;
      if (!this.primaryKey.equals(that.primaryKey))
        return false;
    }

    boolean this_present_attributes = true && this.isSetAttributes();
    boolean that_present_attributes = true && that.isSetAttributes();
    if (this_present_attributes || that_present_attributes) {
      if (!(this_present_attributes && that_present_attributes))
        return false;
      if (!this.attributes.equals(that.attributes))
        return false;
    }

    boolean this_present_locatedServerName = true && this.isSetLocatedServerName();
    boolean that_present_locatedServerName = true && that.isSetLocatedServerName();
    if (this_present_locatedServerName || that_present_locatedServerName) {
      if (!(this_present_locatedServerName && that_present_locatedServerName))
        return false;
      if (!this.locatedServerName.equals(that.locatedServerName))
        return false;
    }

    boolean this_present_locatedServerUrl = true && this.isSetLocatedServerUrl();
    boolean that_present_locatedServerUrl = true && that.isSetLocatedServerUrl();
    if (this_present_locatedServerUrl || that_present_locatedServerUrl) {
      if (!(this_present_locatedServerUrl && that_present_locatedServerUrl))
        return false;
      if (!this.locatedServerUrl.equals(that.locatedServerUrl))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_name = true && (isSetName());
    list.add(present_name);
    if (present_name)
      list.add(name);

    boolean present_primaryKey = true && (isSetPrimaryKey());
    list.add(present_primaryKey);
    if (present_primaryKey)
      list.add(primaryKey);

    boolean present_attributes = true && (isSetAttributes());
    list.add(present_attributes);
    if (present_attributes)
      list.add(attributes);

    boolean present_locatedServerName = true && (isSetLocatedServerName());
    list.add(present_locatedServerName);
    if (present_locatedServerName)
      list.add(locatedServerName);

    boolean present_locatedServerUrl = true && (isSetLocatedServerUrl());
    list.add(present_locatedServerUrl);
    if (present_locatedServerUrl)
      list.add(locatedServerUrl);

    return list.hashCode();
  }

  @Override
  public int compareTo(VTableMeta other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPrimaryKey()).compareTo(other.isSetPrimaryKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrimaryKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.primaryKey, other.primaryKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAttributes()).compareTo(other.isSetAttributes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAttributes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.attributes, other.attributes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLocatedServerName()).compareTo(other.isSetLocatedServerName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocatedServerName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.locatedServerName, other.locatedServerName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLocatedServerUrl()).compareTo(other.isSetLocatedServerUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocatedServerUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.locatedServerUrl, other.locatedServerUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("VTableMeta(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("primaryKey:");
    if (this.primaryKey == null) {
      sb.append("null");
    } else {
      sb.append(this.primaryKey);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("attributes:");
    if (this.attributes == null) {
      sb.append("null");
    } else {
      sb.append(this.attributes);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("locatedServerName:");
    if (this.locatedServerName == null) {
      sb.append("null");
    } else {
      sb.append(this.locatedServerName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("locatedServerUrl:");
    if (this.locatedServerUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.locatedServerUrl);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'name' was not present! Struct: " + toString());
    }
    if (primaryKey == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'primaryKey' was not present! Struct: " + toString());
    }
    if (attributes == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'attributes' was not present! Struct: " + toString());
    }
    if (locatedServerName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'locatedServerName' was not present! Struct: " + toString());
    }
    if (locatedServerUrl == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'locatedServerUrl' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class VTableMetaStandardSchemeFactory implements SchemeFactory {
    public VTableMetaStandardScheme getScheme() {
      return new VTableMetaStandardScheme();
    }
  }

  private static class VTableMetaStandardScheme extends StandardScheme<VTableMeta> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, VTableMeta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PRIMARY_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.primaryKey = iprot.readString();
              struct.setPrimaryKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ATTRIBUTES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.attributes = new ArrayList<VAttribute>(_list8.size);
                VAttribute _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new VAttribute();
                  _elem9.read(iprot);
                  struct.attributes.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setAttributesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LOCATED_SERVER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.locatedServerName = iprot.readString();
              struct.setLocatedServerNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LOCATED_SERVER_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.locatedServerUrl = iprot.readString();
              struct.setLocatedServerUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, VTableMeta struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.primaryKey != null) {
        oprot.writeFieldBegin(PRIMARY_KEY_FIELD_DESC);
        oprot.writeString(struct.primaryKey);
        oprot.writeFieldEnd();
      }
      if (struct.attributes != null) {
        oprot.writeFieldBegin(ATTRIBUTES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.attributes.size()));
          for (VAttribute _iter11 : struct.attributes)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.locatedServerName != null) {
        oprot.writeFieldBegin(LOCATED_SERVER_NAME_FIELD_DESC);
        oprot.writeString(struct.locatedServerName);
        oprot.writeFieldEnd();
      }
      if (struct.locatedServerUrl != null) {
        oprot.writeFieldBegin(LOCATED_SERVER_URL_FIELD_DESC);
        oprot.writeString(struct.locatedServerUrl);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class VTableMetaTupleSchemeFactory implements SchemeFactory {
    public VTableMetaTupleScheme getScheme() {
      return new VTableMetaTupleScheme();
    }
  }

  private static class VTableMetaTupleScheme extends TupleScheme<VTableMeta> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, VTableMeta struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.name);
      oprot.writeString(struct.primaryKey);
      {
        oprot.writeI32(struct.attributes.size());
        for (VAttribute _iter12 : struct.attributes)
        {
          _iter12.write(oprot);
        }
      }
      oprot.writeString(struct.locatedServerName);
      oprot.writeString(struct.locatedServerUrl);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, VTableMeta struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.name = iprot.readString();
      struct.setNameIsSet(true);
      struct.primaryKey = iprot.readString();
      struct.setPrimaryKeyIsSet(true);
      {
        org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.attributes = new ArrayList<VAttribute>(_list13.size);
        VAttribute _elem14;
        for (int _i15 = 0; _i15 < _list13.size; ++_i15)
        {
          _elem14 = new VAttribute();
          _elem14.read(iprot);
          struct.attributes.add(_elem14);
        }
      }
      struct.setAttributesIsSet(true);
      struct.locatedServerName = iprot.readString();
      struct.setLocatedServerNameIsSet(true);
      struct.locatedServerUrl = iprot.readString();
      struct.setLocatedServerUrlIsSet(true);
    }
  }

}

